<Project>
  <PropertyGroup>
    <IMaoVersion>2026.9.9.8</IMaoVersion>
    <IMaoBaselineId>map-baseline-1</IMaoBaselineId>
    <Version>$(IMaoVersion)</Version>
    <AssemblyVersion>$(IMaoVersion)</AssemblyVersion>
    <FileVersion>$(IMaoVersion)</FileVersion>
    <AppxPackageVersion>$(IMaoVersion)</AppxPackageVersion>
  </PropertyGroup>
</Project>
